litellm_settings:
  cache: true
  cache_params:
    local_only: Ture
    type: gptcache
model_list:
- litellm_params:
    api_base: http://10.140.24.111:10086/v1
    api_key: sk-anything
    model: gpt-3.5-turbo
  model_name: gpt-3.5-turbo
